CREATE DATABASE [db_sistema_hotelbs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_sistema_hotelbs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.HOTELBONSSONHOS\MSSQL\DATA\db_sistema_hotelbs.mdf' , SIZE = 1048576KB , FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'db_sistema_hotelbs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.HOTELBONSSONHOS\MSSQL\DATA\db_sistema_hotelbs_log.ldf' , SIZE = 524288KB , MAXSIZE = 10485760KB , FILEGROWTH = 262144KB )
GO
ALTER DATABASE [db_sistema_hotelbs] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [db_sistema_hotelbs] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [db_sistema_hotelbs] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_sistema_hotelbs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_sistema_hotelbs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db_sistema_hotelbs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_sistema_hotelbs] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_sistema_hotelbs] SET  READ_WRITE 
GO
ALTER DATABASE [db_sistema_hotelbs] SET RECOVERY FULL 
GO
ALTER DATABASE [db_sistema_hotelbs] SET  MULTI_USER 
GO
ALTER DATABASE [db_sistema_hotelbs] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_sistema_hotelbs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_sistema_hotelbs] SET DELAYED_DURABILITY = DISABLED 
GO
USE [db_sistema_hotelbs]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [db_sistema_hotelbs]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [db_sistema_hotelbs] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
