USE db_sistema_hotelbs
GO

CREATE TABLE TB_CLIENTES (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
SENHA VARCHAR(260) NOT NULL,
CONSTRAINT UNIQUE_CONST_CLIENTE UNIQUE (CPF, EMAIL)
)

CREATE TABLE TB_USUARIOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    TIPO VARCHAR(13) NOT NULL,
    SENHA VARCHAR(260) NOT NULL,
    CONSTRAINT UQ_EMAIL_USUARIO UNIQUE (EMAIL) 
)

CREATE TABLE TB_TIPO_QUARTO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TIPO_QUARTO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    VALOR_DIARIA DECIMAL(6,2) NOT NULL
)

CREATE TABLE TB_QUARTOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NUMERO INT NOT NULL,
    ANDAR VARCHAR(25) NOT NULL,
    TIPO_ID INT NOT NULL,
    CONSTRAINT FK_QUARTO_TIPO FOREIGN KEY (TIPO_ID) REFERENCES TB_TIPO_QUARTO(ID)
)

CREATE TABLE TB_FOTOS_QUARTO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    URL_FOTO VARCHAR(250),
    ID_QUARTO INT NOT NULL,
    CONSTRAINT FK_FOTO_QUARTO FOREIGN KEY (ID_QUARTO) REFERENCES TB_QUARTOS(ID)
)

CREATE TABLE TB_AVALIACOES (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOTA INT,
    COMENTARIO VARCHAR(500),
    DATA_COMENTARIO SMALLDATETIME,
    ID_QUARTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_AVALIACAO_QUARTO FOREIGN KEY (ID_QUARTO) REFERENCES TB_QUARTOS(ID),
    CONSTRAINT FK_AVALIACAO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES(ID)
)   

CREATE TABLE TB_AGENDAMENTOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DATA_ENTRADA SMALLDATETIME NOT NULL,
    DATA_SAIDA SMALLDATETIME NOT NULL,
    ID_STATUS INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_QUARTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_AGENDAMENTO_STATUS FOREIGN KEY (ID_STATUS) REFERENCES TB_STATUS_AGENDAMENTO(ID),
    CONSTRAINT FK_AGENDAMENTO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES(ID),
    CONSTRAINT FK_AGENDAMENTO_QUARTO FOREIGN KEY (ID_QUARTO) REFERENCES TB_QUARTOS(ID),
    CONSTRAINT FK_AGENDAMENTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS(ID)
)

CREATE TABLE TB_STATUS_AGENDAMENTO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    STATUS VARCHAR(150) NOT NULL,
    DATA_STATUS SMALLDATETIME NOT NULL,
    OBSERVACOES VARCHAR(300)
)

CREATE TABLE TB_ATENDIMENTOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DATA_PAGAMENTO SMALLDATETIME,
    ID_AGENDAMENTO INT NOT NULL,
    CONSTRAINT FK_ATENDIMENTO_AGENDAMENTO FOREIGN KEY (ID_AGENDAMENTO) REFERENCES TB_AGENDAMENTOS(ID)
)