CREATE TABLE TB_CLIENTES (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
SENHA VARCHAR(25) NOT NULL,
CONSTRAINT UNIQUE_CONST_CLIENTE UNIQUE (CPF, EMAIL)
)

